version: '3.1'

services:

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testAccount
    ports:
      - '5432:5432'

  express:
    build: ./
    container_name: express
    restart: always
    ports:
      - '3005:3005'
    expose:
      - 3005
    links:
      - postgresql:postgresql

  react:
    build: ./dashboard-ui/
    container_name: react
    restart: always
    ports:
      - '3000:3000'
    expose:
      - 3000
